apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: php
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`web.292621-xkube.tk`)
    kind: Rule
    services:
    - name: php
      port: 9000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: php-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`web.292621-xkube.tk`)
    kind: Rule
    services:
    - name: php
      port: 9000
  tls:
    certResolver: myresolver