apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ui
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`traefik.292621-xkube.tk`)
    kind: Rule
    services:
    - name: traefik
      port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ui-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`traefik.292621-xkube.tk`)
    kind: Rule
    services:
    - name: traefik
      port: 8080
  tls:
    certResolver: myresolver